/* AUTOGENERATED FILE. DO NOT EDIT. */
#include <string.h>
#include <stdlib.h>
#include <setjmp.h>
#include "cmock.h"
#include "mock_SubStringSearch.h"

static const char* CMockString_findSubstringIndex = "findSubstringIndex";
static const char* CMockString_main_str = "main_str";
static const char* CMockString_sub_str = "sub_str";

typedef struct _CMOCK_findSubstringIndex_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  int ReturnVal;
  int CallOrder;
  const char* Expected_main_str;
  const char* Expected_sub_str;
  char IgnoreArg_main_str;
  char IgnoreArg_sub_str;

} CMOCK_findSubstringIndex_CALL_INSTANCE;

static struct mock_SubStringSearchInstance
{
  char findSubstringIndex_IgnoreBool;
  int findSubstringIndex_FinalReturn;
  char findSubstringIndex_CallbackBool;
  CMOCK_findSubstringIndex_CALLBACK findSubstringIndex_CallbackFunctionPointer;
  int findSubstringIndex_CallbackCalls;
  CMOCK_MEM_INDEX_TYPE findSubstringIndex_CallInstance;
} Mock;

extern jmp_buf AbortFrame;
extern int GlobalExpectCount;
extern int GlobalVerifyOrder;

void mock_SubStringSearch_Verify(void)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_MEM_INDEX_TYPE call_instance;
  call_instance = Mock.findSubstringIndex_CallInstance;
  if (Mock.findSubstringIndex_IgnoreBool)
    call_instance = CMOCK_GUTS_NONE;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_findSubstringIndex);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
  if (Mock.findSubstringIndex_CallbackFunctionPointer != NULL)
  {
    call_instance = CMOCK_GUTS_NONE;
    (void)call_instance;
  }
}

void mock_SubStringSearch_Init(void)
{
  mock_SubStringSearch_Destroy();
}

void mock_SubStringSearch_Destroy(void)
{
  CMock_Guts_MemFreeAll();
  memset(&Mock, 0, sizeof(Mock));
  GlobalExpectCount = 0;
  GlobalVerifyOrder = 0;
}

int findSubstringIndex(const char* main_str, const char* sub_str)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_findSubstringIndex_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_findSubstringIndex);
  cmock_call_instance = (CMOCK_findSubstringIndex_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.findSubstringIndex_CallInstance);
  Mock.findSubstringIndex_CallInstance = CMock_Guts_MemNext(Mock.findSubstringIndex_CallInstance);
  if (Mock.findSubstringIndex_IgnoreBool)
  {
    UNITY_CLR_DETAILS();
    if (cmock_call_instance == NULL)
      return Mock.findSubstringIndex_FinalReturn;
    Mock.findSubstringIndex_FinalReturn = cmock_call_instance->ReturnVal;
    return cmock_call_instance->ReturnVal;
  }
  if (!Mock.findSubstringIndex_CallbackBool &&
      Mock.findSubstringIndex_CallbackFunctionPointer != NULL)
  {
    int cmock_cb_ret = Mock.findSubstringIndex_CallbackFunctionPointer(main_str, sub_str, Mock.findSubstringIndex_CallbackCalls++);
    UNITY_CLR_DETAILS();
    return cmock_cb_ret;
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  if (cmock_call_instance->CallOrder > ++GlobalVerifyOrder)
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledEarly);
  if (cmock_call_instance->CallOrder < GlobalVerifyOrder)
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLate);
  if (!cmock_call_instance->IgnoreArg_main_str)
  {
    UNITY_SET_DETAILS(CMockString_findSubstringIndex,CMockString_main_str);
    UNITY_TEST_ASSERT_EQUAL_STRING(cmock_call_instance->Expected_main_str, main_str, cmock_line, CMockStringMismatch);
  }
  if (!cmock_call_instance->IgnoreArg_sub_str)
  {
    UNITY_SET_DETAILS(CMockString_findSubstringIndex,CMockString_sub_str);
    UNITY_TEST_ASSERT_EQUAL_STRING(cmock_call_instance->Expected_sub_str, sub_str, cmock_line, CMockStringMismatch);
  }
  if (Mock.findSubstringIndex_CallbackFunctionPointer != NULL)
  {
    cmock_call_instance->ReturnVal = Mock.findSubstringIndex_CallbackFunctionPointer(main_str, sub_str, Mock.findSubstringIndex_CallbackCalls++);
  }
  UNITY_CLR_DETAILS();
  return cmock_call_instance->ReturnVal;
}

void CMockExpectParameters_findSubstringIndex(CMOCK_findSubstringIndex_CALL_INSTANCE* cmock_call_instance, const char* main_str, const char* sub_str);
void CMockExpectParameters_findSubstringIndex(CMOCK_findSubstringIndex_CALL_INSTANCE* cmock_call_instance, const char* main_str, const char* sub_str)
{
  cmock_call_instance->Expected_main_str = main_str;
  cmock_call_instance->IgnoreArg_main_str = 0;
  cmock_call_instance->Expected_sub_str = sub_str;
  cmock_call_instance->IgnoreArg_sub_str = 0;
}

void findSubstringIndex_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, int cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_findSubstringIndex_CALL_INSTANCE));
  CMOCK_findSubstringIndex_CALL_INSTANCE* cmock_call_instance = (CMOCK_findSubstringIndex_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.findSubstringIndex_CallInstance = CMock_Guts_MemChain(Mock.findSubstringIndex_CallInstance, cmock_guts_index);
  Mock.findSubstringIndex_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ReturnVal = cmock_to_return;
  Mock.findSubstringIndex_IgnoreBool = (char)1;
}

void findSubstringIndex_CMockStopIgnore(void)
{
  if(Mock.findSubstringIndex_IgnoreBool)
    Mock.findSubstringIndex_CallInstance = CMock_Guts_MemNext(Mock.findSubstringIndex_CallInstance);
  Mock.findSubstringIndex_IgnoreBool = (char)0;
}

void findSubstringIndex_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, const char* main_str, const char* sub_str, int cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_findSubstringIndex_CALL_INSTANCE));
  CMOCK_findSubstringIndex_CALL_INSTANCE* cmock_call_instance = (CMOCK_findSubstringIndex_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.findSubstringIndex_CallInstance = CMock_Guts_MemChain(Mock.findSubstringIndex_CallInstance, cmock_guts_index);
  Mock.findSubstringIndex_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->CallOrder = ++GlobalExpectCount;
  CMockExpectParameters_findSubstringIndex(cmock_call_instance, main_str, sub_str);
  cmock_call_instance->ReturnVal = cmock_to_return;
}

void findSubstringIndex_AddCallback(CMOCK_findSubstringIndex_CALLBACK Callback)
{
  Mock.findSubstringIndex_IgnoreBool = (char)0;
  Mock.findSubstringIndex_CallbackBool = (char)1;
  Mock.findSubstringIndex_CallbackFunctionPointer = Callback;
}

void findSubstringIndex_Stub(CMOCK_findSubstringIndex_CALLBACK Callback)
{
  Mock.findSubstringIndex_IgnoreBool = (char)0;
  Mock.findSubstringIndex_CallbackBool = (char)0;
  Mock.findSubstringIndex_CallbackFunctionPointer = Callback;
}

void findSubstringIndex_CMockIgnoreArg_main_str(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_findSubstringIndex_CALL_INSTANCE* cmock_call_instance = (CMOCK_findSubstringIndex_CALL_INSTANCE*)CMock_Guts_GetAddressFor(CMock_Guts_MemEndOfChain(Mock.findSubstringIndex_CallInstance));
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringIgnPreExp);
  cmock_call_instance->IgnoreArg_main_str = 1;
}

void findSubstringIndex_CMockIgnoreArg_sub_str(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_findSubstringIndex_CALL_INSTANCE* cmock_call_instance = (CMOCK_findSubstringIndex_CALL_INSTANCE*)CMock_Guts_GetAddressFor(CMock_Guts_MemEndOfChain(Mock.findSubstringIndex_CallInstance));
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringIgnPreExp);
  cmock_call_instance->IgnoreArg_sub_str = 1;
}

