/* AUTOGENERATED FILE. DO NOT EDIT. */
#include <string.h>
#include <stdlib.h>
#include <setjmp.h>
#include "cmock.h"
#include "mock_SerialIO.h"

static const char* CMockString_SerialIO_Create = "SerialIO_Create";
static const char* CMockString_SerialIO_Destroy = "SerialIO_Destroy";
static const char* CMockString_SerialIO_IsAvailable = "SerialIO_IsAvailable";
static const char* CMockString_SerialIO_Print = "SerialIO_Print";
static const char* CMockString_SerialIO_Read = "SerialIO_Read";
static const char* CMockString_SerialIO_ReadStringUntil = "SerialIO_ReadStringUntil";
static const char* CMockString_SerialIO_Write = "SerialIO_Write";
static const char* CMockString_baudrate = "baudrate";
static const char* CMockString_buffer = "buffer";
static const char* CMockString_byte = "byte";
static const char* CMockString_end = "end";
static const char* CMockString_number = "number";
static const char* CMockString_serial = "serial";
static const char* CMockString_text = "text";
static const char* CMockString_timeout_ms = "timeout_ms";

typedef struct _CMOCK_SerialIO_Create_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  SerialIO_t ReturnVal;
  int CallOrder;
  int Expected_number;
  uint32_t Expected_baudrate;
  char IgnoreArg_number;
  char IgnoreArg_baudrate;

} CMOCK_SerialIO_Create_CALL_INSTANCE;

typedef struct _CMOCK_SerialIO_Destroy_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  int CallOrder;
  SerialIO_t Expected_serial;
  char IgnoreArg_serial;

} CMOCK_SerialIO_Destroy_CALL_INSTANCE;

typedef struct _CMOCK_SerialIO_Read_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  char ReturnVal;
  int CallOrder;
  SerialIO_t Expected_serial;
  char IgnoreArg_serial;

} CMOCK_SerialIO_Read_CALL_INSTANCE;

typedef struct _CMOCK_SerialIO_Write_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  int CallOrder;
  SerialIO_t Expected_serial;
  char Expected_byte;
  char IgnoreArg_serial;
  char IgnoreArg_byte;

} CMOCK_SerialIO_Write_CALL_INSTANCE;

typedef struct _CMOCK_SerialIO_ReadStringUntil_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  int CallOrder;
  SerialIO_t Expected_serial;
  char* Expected_buffer;
  char Expected_end;
  uint32_t Expected_timeout_ms;
  char ReturnThruPtr_buffer_Used;
  char* ReturnThruPtr_buffer_Val;
  size_t ReturnThruPtr_buffer_Size;
  char IgnoreArg_serial;
  char IgnoreArg_buffer;
  char IgnoreArg_end;
  char IgnoreArg_timeout_ms;

} CMOCK_SerialIO_ReadStringUntil_CALL_INSTANCE;

typedef struct _CMOCK_SerialIO_Print_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  int CallOrder;
  SerialIO_t Expected_serial;
  const char* Expected_text;
  char IgnoreArg_serial;
  char IgnoreArg_text;

} CMOCK_SerialIO_Print_CALL_INSTANCE;

typedef struct _CMOCK_SerialIO_IsAvailable_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  int ReturnVal;
  int CallOrder;
  SerialIO_t Expected_serial;
  char IgnoreArg_serial;

} CMOCK_SerialIO_IsAvailable_CALL_INSTANCE;

static struct mock_SerialIOInstance
{
  char SerialIO_Create_IgnoreBool;
  SerialIO_t SerialIO_Create_FinalReturn;
  char SerialIO_Create_CallbackBool;
  CMOCK_SerialIO_Create_CALLBACK SerialIO_Create_CallbackFunctionPointer;
  int SerialIO_Create_CallbackCalls;
  CMOCK_MEM_INDEX_TYPE SerialIO_Create_CallInstance;
  char SerialIO_Destroy_IgnoreBool;
  char SerialIO_Destroy_CallbackBool;
  CMOCK_SerialIO_Destroy_CALLBACK SerialIO_Destroy_CallbackFunctionPointer;
  int SerialIO_Destroy_CallbackCalls;
  CMOCK_MEM_INDEX_TYPE SerialIO_Destroy_CallInstance;
  char SerialIO_Read_IgnoreBool;
  char SerialIO_Read_FinalReturn;
  char SerialIO_Read_CallbackBool;
  CMOCK_SerialIO_Read_CALLBACK SerialIO_Read_CallbackFunctionPointer;
  int SerialIO_Read_CallbackCalls;
  CMOCK_MEM_INDEX_TYPE SerialIO_Read_CallInstance;
  char SerialIO_Write_IgnoreBool;
  char SerialIO_Write_CallbackBool;
  CMOCK_SerialIO_Write_CALLBACK SerialIO_Write_CallbackFunctionPointer;
  int SerialIO_Write_CallbackCalls;
  CMOCK_MEM_INDEX_TYPE SerialIO_Write_CallInstance;
  char SerialIO_ReadStringUntil_IgnoreBool;
  char SerialIO_ReadStringUntil_CallbackBool;
  CMOCK_SerialIO_ReadStringUntil_CALLBACK SerialIO_ReadStringUntil_CallbackFunctionPointer;
  int SerialIO_ReadStringUntil_CallbackCalls;
  CMOCK_MEM_INDEX_TYPE SerialIO_ReadStringUntil_CallInstance;
  char SerialIO_Print_IgnoreBool;
  char SerialIO_Print_CallbackBool;
  CMOCK_SerialIO_Print_CALLBACK SerialIO_Print_CallbackFunctionPointer;
  int SerialIO_Print_CallbackCalls;
  CMOCK_MEM_INDEX_TYPE SerialIO_Print_CallInstance;
  char SerialIO_IsAvailable_IgnoreBool;
  int SerialIO_IsAvailable_FinalReturn;
  char SerialIO_IsAvailable_CallbackBool;
  CMOCK_SerialIO_IsAvailable_CALLBACK SerialIO_IsAvailable_CallbackFunctionPointer;
  int SerialIO_IsAvailable_CallbackCalls;
  CMOCK_MEM_INDEX_TYPE SerialIO_IsAvailable_CallInstance;
} Mock;

extern jmp_buf AbortFrame;
extern int GlobalExpectCount;
extern int GlobalVerifyOrder;

void mock_SerialIO_Verify(void)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_MEM_INDEX_TYPE call_instance;
  call_instance = Mock.SerialIO_Create_CallInstance;
  if (Mock.SerialIO_Create_IgnoreBool)
    call_instance = CMOCK_GUTS_NONE;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_SerialIO_Create);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
  if (Mock.SerialIO_Create_CallbackFunctionPointer != NULL)
  {
    call_instance = CMOCK_GUTS_NONE;
    (void)call_instance;
  }
  call_instance = Mock.SerialIO_Destroy_CallInstance;
  if (Mock.SerialIO_Destroy_IgnoreBool)
    call_instance = CMOCK_GUTS_NONE;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_SerialIO_Destroy);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
  if (Mock.SerialIO_Destroy_CallbackFunctionPointer != NULL)
  {
    call_instance = CMOCK_GUTS_NONE;
    (void)call_instance;
  }
  call_instance = Mock.SerialIO_Read_CallInstance;
  if (Mock.SerialIO_Read_IgnoreBool)
    call_instance = CMOCK_GUTS_NONE;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_SerialIO_Read);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
  if (Mock.SerialIO_Read_CallbackFunctionPointer != NULL)
  {
    call_instance = CMOCK_GUTS_NONE;
    (void)call_instance;
  }
  call_instance = Mock.SerialIO_Write_CallInstance;
  if (Mock.SerialIO_Write_IgnoreBool)
    call_instance = CMOCK_GUTS_NONE;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_SerialIO_Write);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
  if (Mock.SerialIO_Write_CallbackFunctionPointer != NULL)
  {
    call_instance = CMOCK_GUTS_NONE;
    (void)call_instance;
  }
  call_instance = Mock.SerialIO_ReadStringUntil_CallInstance;
  if (Mock.SerialIO_ReadStringUntil_IgnoreBool)
    call_instance = CMOCK_GUTS_NONE;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_SerialIO_ReadStringUntil);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
  if (Mock.SerialIO_ReadStringUntil_CallbackFunctionPointer != NULL)
  {
    call_instance = CMOCK_GUTS_NONE;
    (void)call_instance;
  }
  call_instance = Mock.SerialIO_Print_CallInstance;
  if (Mock.SerialIO_Print_IgnoreBool)
    call_instance = CMOCK_GUTS_NONE;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_SerialIO_Print);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
  if (Mock.SerialIO_Print_CallbackFunctionPointer != NULL)
  {
    call_instance = CMOCK_GUTS_NONE;
    (void)call_instance;
  }
  call_instance = Mock.SerialIO_IsAvailable_CallInstance;
  if (Mock.SerialIO_IsAvailable_IgnoreBool)
    call_instance = CMOCK_GUTS_NONE;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_SerialIO_IsAvailable);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
  if (Mock.SerialIO_IsAvailable_CallbackFunctionPointer != NULL)
  {
    call_instance = CMOCK_GUTS_NONE;
    (void)call_instance;
  }
}

void mock_SerialIO_Init(void)
{
  mock_SerialIO_Destroy();
}

void mock_SerialIO_Destroy(void)
{
  CMock_Guts_MemFreeAll();
  memset(&Mock, 0, sizeof(Mock));
  GlobalExpectCount = 0;
  GlobalVerifyOrder = 0;
}

SerialIO_t SerialIO_Create(int number, uint32_t baudrate)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_SerialIO_Create_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_SerialIO_Create);
  cmock_call_instance = (CMOCK_SerialIO_Create_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.SerialIO_Create_CallInstance);
  Mock.SerialIO_Create_CallInstance = CMock_Guts_MemNext(Mock.SerialIO_Create_CallInstance);
  if (Mock.SerialIO_Create_IgnoreBool)
  {
    UNITY_CLR_DETAILS();
    if (cmock_call_instance == NULL)
      return Mock.SerialIO_Create_FinalReturn;
    memcpy((void*)(&Mock.SerialIO_Create_FinalReturn), (void*)(&cmock_call_instance->ReturnVal),
         sizeof(SerialIO_t[sizeof(cmock_call_instance->ReturnVal) == sizeof(SerialIO_t) ? 1 : -1])); /* add SerialIO_t to :treat_as_array if this causes an error */
    return cmock_call_instance->ReturnVal;
  }
  if (!Mock.SerialIO_Create_CallbackBool &&
      Mock.SerialIO_Create_CallbackFunctionPointer != NULL)
  {
    SerialIO_t cmock_cb_ret = Mock.SerialIO_Create_CallbackFunctionPointer(number, baudrate, Mock.SerialIO_Create_CallbackCalls++);
    UNITY_CLR_DETAILS();
    return cmock_cb_ret;
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  if (cmock_call_instance->CallOrder > ++GlobalVerifyOrder)
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledEarly);
  if (cmock_call_instance->CallOrder < GlobalVerifyOrder)
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLate);
  if (!cmock_call_instance->IgnoreArg_number)
  {
    UNITY_SET_DETAILS(CMockString_SerialIO_Create,CMockString_number);
    UNITY_TEST_ASSERT_EQUAL_INT(cmock_call_instance->Expected_number, number, cmock_line, CMockStringMismatch);
  }
  if (!cmock_call_instance->IgnoreArg_baudrate)
  {
    UNITY_SET_DETAILS(CMockString_SerialIO_Create,CMockString_baudrate);
    UNITY_TEST_ASSERT_EQUAL_HEX32(cmock_call_instance->Expected_baudrate, baudrate, cmock_line, CMockStringMismatch);
  }
  if (Mock.SerialIO_Create_CallbackFunctionPointer != NULL)
  {
    cmock_call_instance->ReturnVal = Mock.SerialIO_Create_CallbackFunctionPointer(number, baudrate, Mock.SerialIO_Create_CallbackCalls++);
  }
  UNITY_CLR_DETAILS();
  return cmock_call_instance->ReturnVal;
}

void CMockExpectParameters_SerialIO_Create(CMOCK_SerialIO_Create_CALL_INSTANCE* cmock_call_instance, int number, uint32_t baudrate);
void CMockExpectParameters_SerialIO_Create(CMOCK_SerialIO_Create_CALL_INSTANCE* cmock_call_instance, int number, uint32_t baudrate)
{
  cmock_call_instance->Expected_number = number;
  cmock_call_instance->IgnoreArg_number = 0;
  cmock_call_instance->Expected_baudrate = baudrate;
  cmock_call_instance->IgnoreArg_baudrate = 0;
}

void SerialIO_Create_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, SerialIO_t cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_SerialIO_Create_CALL_INSTANCE));
  CMOCK_SerialIO_Create_CALL_INSTANCE* cmock_call_instance = (CMOCK_SerialIO_Create_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.SerialIO_Create_CallInstance = CMock_Guts_MemChain(Mock.SerialIO_Create_CallInstance, cmock_guts_index);
  Mock.SerialIO_Create_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ReturnVal = cmock_to_return;
  Mock.SerialIO_Create_IgnoreBool = (char)1;
}

void SerialIO_Create_CMockStopIgnore(void)
{
  if(Mock.SerialIO_Create_IgnoreBool)
    Mock.SerialIO_Create_CallInstance = CMock_Guts_MemNext(Mock.SerialIO_Create_CallInstance);
  Mock.SerialIO_Create_IgnoreBool = (char)0;
}

void SerialIO_Create_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, int number, uint32_t baudrate, SerialIO_t cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_SerialIO_Create_CALL_INSTANCE));
  CMOCK_SerialIO_Create_CALL_INSTANCE* cmock_call_instance = (CMOCK_SerialIO_Create_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.SerialIO_Create_CallInstance = CMock_Guts_MemChain(Mock.SerialIO_Create_CallInstance, cmock_guts_index);
  Mock.SerialIO_Create_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->CallOrder = ++GlobalExpectCount;
  CMockExpectParameters_SerialIO_Create(cmock_call_instance, number, baudrate);
  memcpy((void*)(&cmock_call_instance->ReturnVal), (void*)(&cmock_to_return),
         sizeof(SerialIO_t[sizeof(cmock_to_return) == sizeof(SerialIO_t) ? 1 : -1])); /* add SerialIO_t to :treat_as_array if this causes an error */
}

void SerialIO_Create_AddCallback(CMOCK_SerialIO_Create_CALLBACK Callback)
{
  Mock.SerialIO_Create_IgnoreBool = (char)0;
  Mock.SerialIO_Create_CallbackBool = (char)1;
  Mock.SerialIO_Create_CallbackFunctionPointer = Callback;
}

void SerialIO_Create_Stub(CMOCK_SerialIO_Create_CALLBACK Callback)
{
  Mock.SerialIO_Create_IgnoreBool = (char)0;
  Mock.SerialIO_Create_CallbackBool = (char)0;
  Mock.SerialIO_Create_CallbackFunctionPointer = Callback;
}

void SerialIO_Create_CMockIgnoreArg_number(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_SerialIO_Create_CALL_INSTANCE* cmock_call_instance = (CMOCK_SerialIO_Create_CALL_INSTANCE*)CMock_Guts_GetAddressFor(CMock_Guts_MemEndOfChain(Mock.SerialIO_Create_CallInstance));
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringIgnPreExp);
  cmock_call_instance->IgnoreArg_number = 1;
}

void SerialIO_Create_CMockIgnoreArg_baudrate(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_SerialIO_Create_CALL_INSTANCE* cmock_call_instance = (CMOCK_SerialIO_Create_CALL_INSTANCE*)CMock_Guts_GetAddressFor(CMock_Guts_MemEndOfChain(Mock.SerialIO_Create_CallInstance));
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringIgnPreExp);
  cmock_call_instance->IgnoreArg_baudrate = 1;
}

void SerialIO_Destroy(SerialIO_t serial)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_SerialIO_Destroy_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_SerialIO_Destroy);
  cmock_call_instance = (CMOCK_SerialIO_Destroy_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.SerialIO_Destroy_CallInstance);
  Mock.SerialIO_Destroy_CallInstance = CMock_Guts_MemNext(Mock.SerialIO_Destroy_CallInstance);
  if (Mock.SerialIO_Destroy_IgnoreBool)
  {
    UNITY_CLR_DETAILS();
    return;
  }
  if (!Mock.SerialIO_Destroy_CallbackBool &&
      Mock.SerialIO_Destroy_CallbackFunctionPointer != NULL)
  {
    Mock.SerialIO_Destroy_CallbackFunctionPointer(serial, Mock.SerialIO_Destroy_CallbackCalls++);
    UNITY_CLR_DETAILS();
    return;
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  if (cmock_call_instance->CallOrder > ++GlobalVerifyOrder)
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledEarly);
  if (cmock_call_instance->CallOrder < GlobalVerifyOrder)
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLate);
  if (!cmock_call_instance->IgnoreArg_serial)
  {
    UNITY_SET_DETAILS(CMockString_SerialIO_Destroy,CMockString_serial);
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(&cmock_call_instance->Expected_serial), (void*)(&serial), sizeof(SerialIO_t), cmock_line, CMockStringMismatch);
  }
  if (Mock.SerialIO_Destroy_CallbackFunctionPointer != NULL)
  {
    Mock.SerialIO_Destroy_CallbackFunctionPointer(serial, Mock.SerialIO_Destroy_CallbackCalls++);
  }
  UNITY_CLR_DETAILS();
}

void CMockExpectParameters_SerialIO_Destroy(CMOCK_SerialIO_Destroy_CALL_INSTANCE* cmock_call_instance, SerialIO_t serial);
void CMockExpectParameters_SerialIO_Destroy(CMOCK_SerialIO_Destroy_CALL_INSTANCE* cmock_call_instance, SerialIO_t serial)
{
  memcpy((void*)(&cmock_call_instance->Expected_serial), (void*)(&serial),
         sizeof(SerialIO_t[sizeof(serial) == sizeof(SerialIO_t) ? 1 : -1])); /* add SerialIO_t to :treat_as_array if this causes an error */
  cmock_call_instance->IgnoreArg_serial = 0;
}

void SerialIO_Destroy_CMockIgnore(void)
{
  Mock.SerialIO_Destroy_IgnoreBool = (char)1;
}

void SerialIO_Destroy_CMockStopIgnore(void)
{
  Mock.SerialIO_Destroy_IgnoreBool = (char)0;
}

void SerialIO_Destroy_CMockExpect(UNITY_LINE_TYPE cmock_line, SerialIO_t serial)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_SerialIO_Destroy_CALL_INSTANCE));
  CMOCK_SerialIO_Destroy_CALL_INSTANCE* cmock_call_instance = (CMOCK_SerialIO_Destroy_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.SerialIO_Destroy_CallInstance = CMock_Guts_MemChain(Mock.SerialIO_Destroy_CallInstance, cmock_guts_index);
  Mock.SerialIO_Destroy_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->CallOrder = ++GlobalExpectCount;
  CMockExpectParameters_SerialIO_Destroy(cmock_call_instance, serial);
}

void SerialIO_Destroy_AddCallback(CMOCK_SerialIO_Destroy_CALLBACK Callback)
{
  Mock.SerialIO_Destroy_IgnoreBool = (char)0;
  Mock.SerialIO_Destroy_CallbackBool = (char)1;
  Mock.SerialIO_Destroy_CallbackFunctionPointer = Callback;
}

void SerialIO_Destroy_Stub(CMOCK_SerialIO_Destroy_CALLBACK Callback)
{
  Mock.SerialIO_Destroy_IgnoreBool = (char)0;
  Mock.SerialIO_Destroy_CallbackBool = (char)0;
  Mock.SerialIO_Destroy_CallbackFunctionPointer = Callback;
}

void SerialIO_Destroy_CMockIgnoreArg_serial(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_SerialIO_Destroy_CALL_INSTANCE* cmock_call_instance = (CMOCK_SerialIO_Destroy_CALL_INSTANCE*)CMock_Guts_GetAddressFor(CMock_Guts_MemEndOfChain(Mock.SerialIO_Destroy_CallInstance));
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringIgnPreExp);
  cmock_call_instance->IgnoreArg_serial = 1;
}

char SerialIO_Read(SerialIO_t serial)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_SerialIO_Read_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_SerialIO_Read);
  cmock_call_instance = (CMOCK_SerialIO_Read_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.SerialIO_Read_CallInstance);
  Mock.SerialIO_Read_CallInstance = CMock_Guts_MemNext(Mock.SerialIO_Read_CallInstance);
  if (Mock.SerialIO_Read_IgnoreBool)
  {
    UNITY_CLR_DETAILS();
    if (cmock_call_instance == NULL)
      return Mock.SerialIO_Read_FinalReturn;
    Mock.SerialIO_Read_FinalReturn = cmock_call_instance->ReturnVal;
    return cmock_call_instance->ReturnVal;
  }
  if (!Mock.SerialIO_Read_CallbackBool &&
      Mock.SerialIO_Read_CallbackFunctionPointer != NULL)
  {
    char cmock_cb_ret = Mock.SerialIO_Read_CallbackFunctionPointer(serial, Mock.SerialIO_Read_CallbackCalls++);
    UNITY_CLR_DETAILS();
    return cmock_cb_ret;
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  if (cmock_call_instance->CallOrder > ++GlobalVerifyOrder)
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledEarly);
  if (cmock_call_instance->CallOrder < GlobalVerifyOrder)
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLate);
  if (!cmock_call_instance->IgnoreArg_serial)
  {
    UNITY_SET_DETAILS(CMockString_SerialIO_Read,CMockString_serial);
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(&cmock_call_instance->Expected_serial), (void*)(&serial), sizeof(SerialIO_t), cmock_line, CMockStringMismatch);
  }
  if (Mock.SerialIO_Read_CallbackFunctionPointer != NULL)
  {
    cmock_call_instance->ReturnVal = Mock.SerialIO_Read_CallbackFunctionPointer(serial, Mock.SerialIO_Read_CallbackCalls++);
  }
  UNITY_CLR_DETAILS();
  return cmock_call_instance->ReturnVal;
}

void CMockExpectParameters_SerialIO_Read(CMOCK_SerialIO_Read_CALL_INSTANCE* cmock_call_instance, SerialIO_t serial);
void CMockExpectParameters_SerialIO_Read(CMOCK_SerialIO_Read_CALL_INSTANCE* cmock_call_instance, SerialIO_t serial)
{
  memcpy((void*)(&cmock_call_instance->Expected_serial), (void*)(&serial),
         sizeof(SerialIO_t[sizeof(serial) == sizeof(SerialIO_t) ? 1 : -1])); /* add SerialIO_t to :treat_as_array if this causes an error */
  cmock_call_instance->IgnoreArg_serial = 0;
}

void SerialIO_Read_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, char cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_SerialIO_Read_CALL_INSTANCE));
  CMOCK_SerialIO_Read_CALL_INSTANCE* cmock_call_instance = (CMOCK_SerialIO_Read_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.SerialIO_Read_CallInstance = CMock_Guts_MemChain(Mock.SerialIO_Read_CallInstance, cmock_guts_index);
  Mock.SerialIO_Read_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ReturnVal = cmock_to_return;
  Mock.SerialIO_Read_IgnoreBool = (char)1;
}

void SerialIO_Read_CMockStopIgnore(void)
{
  if(Mock.SerialIO_Read_IgnoreBool)
    Mock.SerialIO_Read_CallInstance = CMock_Guts_MemNext(Mock.SerialIO_Read_CallInstance);
  Mock.SerialIO_Read_IgnoreBool = (char)0;
}

void SerialIO_Read_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, SerialIO_t serial, char cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_SerialIO_Read_CALL_INSTANCE));
  CMOCK_SerialIO_Read_CALL_INSTANCE* cmock_call_instance = (CMOCK_SerialIO_Read_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.SerialIO_Read_CallInstance = CMock_Guts_MemChain(Mock.SerialIO_Read_CallInstance, cmock_guts_index);
  Mock.SerialIO_Read_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->CallOrder = ++GlobalExpectCount;
  CMockExpectParameters_SerialIO_Read(cmock_call_instance, serial);
  cmock_call_instance->ReturnVal = cmock_to_return;
}

void SerialIO_Read_AddCallback(CMOCK_SerialIO_Read_CALLBACK Callback)
{
  Mock.SerialIO_Read_IgnoreBool = (char)0;
  Mock.SerialIO_Read_CallbackBool = (char)1;
  Mock.SerialIO_Read_CallbackFunctionPointer = Callback;
}

void SerialIO_Read_Stub(CMOCK_SerialIO_Read_CALLBACK Callback)
{
  Mock.SerialIO_Read_IgnoreBool = (char)0;
  Mock.SerialIO_Read_CallbackBool = (char)0;
  Mock.SerialIO_Read_CallbackFunctionPointer = Callback;
}

void SerialIO_Read_CMockIgnoreArg_serial(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_SerialIO_Read_CALL_INSTANCE* cmock_call_instance = (CMOCK_SerialIO_Read_CALL_INSTANCE*)CMock_Guts_GetAddressFor(CMock_Guts_MemEndOfChain(Mock.SerialIO_Read_CallInstance));
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringIgnPreExp);
  cmock_call_instance->IgnoreArg_serial = 1;
}

void SerialIO_Write(SerialIO_t serial, char byte)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_SerialIO_Write_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_SerialIO_Write);
  cmock_call_instance = (CMOCK_SerialIO_Write_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.SerialIO_Write_CallInstance);
  Mock.SerialIO_Write_CallInstance = CMock_Guts_MemNext(Mock.SerialIO_Write_CallInstance);
  if (Mock.SerialIO_Write_IgnoreBool)
  {
    UNITY_CLR_DETAILS();
    return;
  }
  if (!Mock.SerialIO_Write_CallbackBool &&
      Mock.SerialIO_Write_CallbackFunctionPointer != NULL)
  {
    Mock.SerialIO_Write_CallbackFunctionPointer(serial, byte, Mock.SerialIO_Write_CallbackCalls++);
    UNITY_CLR_DETAILS();
    return;
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  if (cmock_call_instance->CallOrder > ++GlobalVerifyOrder)
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledEarly);
  if (cmock_call_instance->CallOrder < GlobalVerifyOrder)
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLate);
  if (!cmock_call_instance->IgnoreArg_serial)
  {
    UNITY_SET_DETAILS(CMockString_SerialIO_Write,CMockString_serial);
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(&cmock_call_instance->Expected_serial), (void*)(&serial), sizeof(SerialIO_t), cmock_line, CMockStringMismatch);
  }
  if (!cmock_call_instance->IgnoreArg_byte)
  {
    UNITY_SET_DETAILS(CMockString_SerialIO_Write,CMockString_byte);
    UNITY_TEST_ASSERT_EQUAL_INT8(cmock_call_instance->Expected_byte, byte, cmock_line, CMockStringMismatch);
  }
  if (Mock.SerialIO_Write_CallbackFunctionPointer != NULL)
  {
    Mock.SerialIO_Write_CallbackFunctionPointer(serial, byte, Mock.SerialIO_Write_CallbackCalls++);
  }
  UNITY_CLR_DETAILS();
}

void CMockExpectParameters_SerialIO_Write(CMOCK_SerialIO_Write_CALL_INSTANCE* cmock_call_instance, SerialIO_t serial, char byte);
void CMockExpectParameters_SerialIO_Write(CMOCK_SerialIO_Write_CALL_INSTANCE* cmock_call_instance, SerialIO_t serial, char byte)
{
  memcpy((void*)(&cmock_call_instance->Expected_serial), (void*)(&serial),
         sizeof(SerialIO_t[sizeof(serial) == sizeof(SerialIO_t) ? 1 : -1])); /* add SerialIO_t to :treat_as_array if this causes an error */
  cmock_call_instance->IgnoreArg_serial = 0;
  cmock_call_instance->Expected_byte = byte;
  cmock_call_instance->IgnoreArg_byte = 0;
}

void SerialIO_Write_CMockIgnore(void)
{
  Mock.SerialIO_Write_IgnoreBool = (char)1;
}

void SerialIO_Write_CMockStopIgnore(void)
{
  Mock.SerialIO_Write_IgnoreBool = (char)0;
}

void SerialIO_Write_CMockExpect(UNITY_LINE_TYPE cmock_line, SerialIO_t serial, char byte)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_SerialIO_Write_CALL_INSTANCE));
  CMOCK_SerialIO_Write_CALL_INSTANCE* cmock_call_instance = (CMOCK_SerialIO_Write_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.SerialIO_Write_CallInstance = CMock_Guts_MemChain(Mock.SerialIO_Write_CallInstance, cmock_guts_index);
  Mock.SerialIO_Write_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->CallOrder = ++GlobalExpectCount;
  CMockExpectParameters_SerialIO_Write(cmock_call_instance, serial, byte);
}

void SerialIO_Write_AddCallback(CMOCK_SerialIO_Write_CALLBACK Callback)
{
  Mock.SerialIO_Write_IgnoreBool = (char)0;
  Mock.SerialIO_Write_CallbackBool = (char)1;
  Mock.SerialIO_Write_CallbackFunctionPointer = Callback;
}

void SerialIO_Write_Stub(CMOCK_SerialIO_Write_CALLBACK Callback)
{
  Mock.SerialIO_Write_IgnoreBool = (char)0;
  Mock.SerialIO_Write_CallbackBool = (char)0;
  Mock.SerialIO_Write_CallbackFunctionPointer = Callback;
}

void SerialIO_Write_CMockIgnoreArg_serial(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_SerialIO_Write_CALL_INSTANCE* cmock_call_instance = (CMOCK_SerialIO_Write_CALL_INSTANCE*)CMock_Guts_GetAddressFor(CMock_Guts_MemEndOfChain(Mock.SerialIO_Write_CallInstance));
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringIgnPreExp);
  cmock_call_instance->IgnoreArg_serial = 1;
}

void SerialIO_Write_CMockIgnoreArg_byte(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_SerialIO_Write_CALL_INSTANCE* cmock_call_instance = (CMOCK_SerialIO_Write_CALL_INSTANCE*)CMock_Guts_GetAddressFor(CMock_Guts_MemEndOfChain(Mock.SerialIO_Write_CallInstance));
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringIgnPreExp);
  cmock_call_instance->IgnoreArg_byte = 1;
}

void SerialIO_ReadStringUntil(SerialIO_t serial, char* buffer, char end, uint32_t timeout_ms)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_SerialIO_ReadStringUntil_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_SerialIO_ReadStringUntil);
  cmock_call_instance = (CMOCK_SerialIO_ReadStringUntil_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.SerialIO_ReadStringUntil_CallInstance);
  Mock.SerialIO_ReadStringUntil_CallInstance = CMock_Guts_MemNext(Mock.SerialIO_ReadStringUntil_CallInstance);
  if (Mock.SerialIO_ReadStringUntil_IgnoreBool)
  {
    UNITY_CLR_DETAILS();
    return;
  }
  if (!Mock.SerialIO_ReadStringUntil_CallbackBool &&
      Mock.SerialIO_ReadStringUntil_CallbackFunctionPointer != NULL)
  {
    Mock.SerialIO_ReadStringUntil_CallbackFunctionPointer(serial, buffer, end, timeout_ms, Mock.SerialIO_ReadStringUntil_CallbackCalls++);
    UNITY_CLR_DETAILS();
    return;
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  if (cmock_call_instance->CallOrder > ++GlobalVerifyOrder)
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledEarly);
  if (cmock_call_instance->CallOrder < GlobalVerifyOrder)
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLate);
  if (!cmock_call_instance->IgnoreArg_serial)
  {
    UNITY_SET_DETAILS(CMockString_SerialIO_ReadStringUntil,CMockString_serial);
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(&cmock_call_instance->Expected_serial), (void*)(&serial), sizeof(SerialIO_t), cmock_line, CMockStringMismatch);
  }
  if (!cmock_call_instance->IgnoreArg_buffer)
  {
    UNITY_SET_DETAILS(CMockString_SerialIO_ReadStringUntil,CMockString_buffer);
    UNITY_TEST_ASSERT_EQUAL_STRING(cmock_call_instance->Expected_buffer, buffer, cmock_line, CMockStringMismatch);
  }
  if (!cmock_call_instance->IgnoreArg_end)
  {
    UNITY_SET_DETAILS(CMockString_SerialIO_ReadStringUntil,CMockString_end);
    UNITY_TEST_ASSERT_EQUAL_INT8(cmock_call_instance->Expected_end, end, cmock_line, CMockStringMismatch);
  }
  if (!cmock_call_instance->IgnoreArg_timeout_ms)
  {
    UNITY_SET_DETAILS(CMockString_SerialIO_ReadStringUntil,CMockString_timeout_ms);
    UNITY_TEST_ASSERT_EQUAL_HEX32(cmock_call_instance->Expected_timeout_ms, timeout_ms, cmock_line, CMockStringMismatch);
  }
  if (Mock.SerialIO_ReadStringUntil_CallbackFunctionPointer != NULL)
  {
    Mock.SerialIO_ReadStringUntil_CallbackFunctionPointer(serial, buffer, end, timeout_ms, Mock.SerialIO_ReadStringUntil_CallbackCalls++);
  }
  if (cmock_call_instance->ReturnThruPtr_buffer_Used)
  {
    UNITY_TEST_ASSERT_NOT_NULL(buffer, cmock_line, CMockStringPtrIsNULL);
    memcpy((void*)buffer, (void*)cmock_call_instance->ReturnThruPtr_buffer_Val,
      cmock_call_instance->ReturnThruPtr_buffer_Size);
  }
  UNITY_CLR_DETAILS();
}

void CMockExpectParameters_SerialIO_ReadStringUntil(CMOCK_SerialIO_ReadStringUntil_CALL_INSTANCE* cmock_call_instance, SerialIO_t serial, char* buffer, char end, uint32_t timeout_ms);
void CMockExpectParameters_SerialIO_ReadStringUntil(CMOCK_SerialIO_ReadStringUntil_CALL_INSTANCE* cmock_call_instance, SerialIO_t serial, char* buffer, char end, uint32_t timeout_ms)
{
  memcpy((void*)(&cmock_call_instance->Expected_serial), (void*)(&serial),
         sizeof(SerialIO_t[sizeof(serial) == sizeof(SerialIO_t) ? 1 : -1])); /* add SerialIO_t to :treat_as_array if this causes an error */
  cmock_call_instance->IgnoreArg_serial = 0;
  cmock_call_instance->Expected_buffer = buffer;
  cmock_call_instance->IgnoreArg_buffer = 0;
  cmock_call_instance->ReturnThruPtr_buffer_Used = 0;
  cmock_call_instance->Expected_end = end;
  cmock_call_instance->IgnoreArg_end = 0;
  cmock_call_instance->Expected_timeout_ms = timeout_ms;
  cmock_call_instance->IgnoreArg_timeout_ms = 0;
}

void SerialIO_ReadStringUntil_CMockIgnore(void)
{
  Mock.SerialIO_ReadStringUntil_IgnoreBool = (char)1;
}

void SerialIO_ReadStringUntil_CMockStopIgnore(void)
{
  Mock.SerialIO_ReadStringUntil_IgnoreBool = (char)0;
}

void SerialIO_ReadStringUntil_CMockExpect(UNITY_LINE_TYPE cmock_line, SerialIO_t serial, char* buffer, char end, uint32_t timeout_ms)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_SerialIO_ReadStringUntil_CALL_INSTANCE));
  CMOCK_SerialIO_ReadStringUntil_CALL_INSTANCE* cmock_call_instance = (CMOCK_SerialIO_ReadStringUntil_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.SerialIO_ReadStringUntil_CallInstance = CMock_Guts_MemChain(Mock.SerialIO_ReadStringUntil_CallInstance, cmock_guts_index);
  Mock.SerialIO_ReadStringUntil_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->CallOrder = ++GlobalExpectCount;
  CMockExpectParameters_SerialIO_ReadStringUntil(cmock_call_instance, serial, buffer, end, timeout_ms);
}

void SerialIO_ReadStringUntil_AddCallback(CMOCK_SerialIO_ReadStringUntil_CALLBACK Callback)
{
  Mock.SerialIO_ReadStringUntil_IgnoreBool = (char)0;
  Mock.SerialIO_ReadStringUntil_CallbackBool = (char)1;
  Mock.SerialIO_ReadStringUntil_CallbackFunctionPointer = Callback;
}

void SerialIO_ReadStringUntil_Stub(CMOCK_SerialIO_ReadStringUntil_CALLBACK Callback)
{
  Mock.SerialIO_ReadStringUntil_IgnoreBool = (char)0;
  Mock.SerialIO_ReadStringUntil_CallbackBool = (char)0;
  Mock.SerialIO_ReadStringUntil_CallbackFunctionPointer = Callback;
}

void SerialIO_ReadStringUntil_CMockReturnMemThruPtr_buffer(UNITY_LINE_TYPE cmock_line, char* buffer, size_t cmock_size)
{
  CMOCK_SerialIO_ReadStringUntil_CALL_INSTANCE* cmock_call_instance = (CMOCK_SerialIO_ReadStringUntil_CALL_INSTANCE*)CMock_Guts_GetAddressFor(CMock_Guts_MemEndOfChain(Mock.SerialIO_ReadStringUntil_CallInstance));
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringPtrPreExp);
  cmock_call_instance->ReturnThruPtr_buffer_Used = 1;
  cmock_call_instance->ReturnThruPtr_buffer_Val = buffer;
  cmock_call_instance->ReturnThruPtr_buffer_Size = cmock_size;
}

void SerialIO_ReadStringUntil_CMockIgnoreArg_serial(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_SerialIO_ReadStringUntil_CALL_INSTANCE* cmock_call_instance = (CMOCK_SerialIO_ReadStringUntil_CALL_INSTANCE*)CMock_Guts_GetAddressFor(CMock_Guts_MemEndOfChain(Mock.SerialIO_ReadStringUntil_CallInstance));
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringIgnPreExp);
  cmock_call_instance->IgnoreArg_serial = 1;
}

void SerialIO_ReadStringUntil_CMockIgnoreArg_buffer(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_SerialIO_ReadStringUntil_CALL_INSTANCE* cmock_call_instance = (CMOCK_SerialIO_ReadStringUntil_CALL_INSTANCE*)CMock_Guts_GetAddressFor(CMock_Guts_MemEndOfChain(Mock.SerialIO_ReadStringUntil_CallInstance));
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringIgnPreExp);
  cmock_call_instance->IgnoreArg_buffer = 1;
}

void SerialIO_ReadStringUntil_CMockIgnoreArg_end(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_SerialIO_ReadStringUntil_CALL_INSTANCE* cmock_call_instance = (CMOCK_SerialIO_ReadStringUntil_CALL_INSTANCE*)CMock_Guts_GetAddressFor(CMock_Guts_MemEndOfChain(Mock.SerialIO_ReadStringUntil_CallInstance));
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringIgnPreExp);
  cmock_call_instance->IgnoreArg_end = 1;
}

void SerialIO_ReadStringUntil_CMockIgnoreArg_timeout_ms(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_SerialIO_ReadStringUntil_CALL_INSTANCE* cmock_call_instance = (CMOCK_SerialIO_ReadStringUntil_CALL_INSTANCE*)CMock_Guts_GetAddressFor(CMock_Guts_MemEndOfChain(Mock.SerialIO_ReadStringUntil_CallInstance));
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringIgnPreExp);
  cmock_call_instance->IgnoreArg_timeout_ms = 1;
}

void SerialIO_Print(SerialIO_t serial, const char* text)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_SerialIO_Print_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_SerialIO_Print);
  cmock_call_instance = (CMOCK_SerialIO_Print_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.SerialIO_Print_CallInstance);
  Mock.SerialIO_Print_CallInstance = CMock_Guts_MemNext(Mock.SerialIO_Print_CallInstance);
  if (Mock.SerialIO_Print_IgnoreBool)
  {
    UNITY_CLR_DETAILS();
    return;
  }
  if (!Mock.SerialIO_Print_CallbackBool &&
      Mock.SerialIO_Print_CallbackFunctionPointer != NULL)
  {
    Mock.SerialIO_Print_CallbackFunctionPointer(serial, text, Mock.SerialIO_Print_CallbackCalls++);
    UNITY_CLR_DETAILS();
    return;
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  if (cmock_call_instance->CallOrder > ++GlobalVerifyOrder)
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledEarly);
  if (cmock_call_instance->CallOrder < GlobalVerifyOrder)
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLate);
  if (!cmock_call_instance->IgnoreArg_serial)
  {
    UNITY_SET_DETAILS(CMockString_SerialIO_Print,CMockString_serial);
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(&cmock_call_instance->Expected_serial), (void*)(&serial), sizeof(SerialIO_t), cmock_line, CMockStringMismatch);
  }
  if (!cmock_call_instance->IgnoreArg_text)
  {
    UNITY_SET_DETAILS(CMockString_SerialIO_Print,CMockString_text);
    UNITY_TEST_ASSERT_EQUAL_STRING(cmock_call_instance->Expected_text, text, cmock_line, CMockStringMismatch);
  }
  if (Mock.SerialIO_Print_CallbackFunctionPointer != NULL)
  {
    Mock.SerialIO_Print_CallbackFunctionPointer(serial, text, Mock.SerialIO_Print_CallbackCalls++);
  }
  UNITY_CLR_DETAILS();
}

void CMockExpectParameters_SerialIO_Print(CMOCK_SerialIO_Print_CALL_INSTANCE* cmock_call_instance, SerialIO_t serial, const char* text);
void CMockExpectParameters_SerialIO_Print(CMOCK_SerialIO_Print_CALL_INSTANCE* cmock_call_instance, SerialIO_t serial, const char* text)
{
  memcpy((void*)(&cmock_call_instance->Expected_serial), (void*)(&serial),
         sizeof(SerialIO_t[sizeof(serial) == sizeof(SerialIO_t) ? 1 : -1])); /* add SerialIO_t to :treat_as_array if this causes an error */
  cmock_call_instance->IgnoreArg_serial = 0;
  cmock_call_instance->Expected_text = text;
  cmock_call_instance->IgnoreArg_text = 0;
}

void SerialIO_Print_CMockIgnore(void)
{
  Mock.SerialIO_Print_IgnoreBool = (char)1;
}

void SerialIO_Print_CMockStopIgnore(void)
{
  Mock.SerialIO_Print_IgnoreBool = (char)0;
}

void SerialIO_Print_CMockExpect(UNITY_LINE_TYPE cmock_line, SerialIO_t serial, const char* text)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_SerialIO_Print_CALL_INSTANCE));
  CMOCK_SerialIO_Print_CALL_INSTANCE* cmock_call_instance = (CMOCK_SerialIO_Print_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.SerialIO_Print_CallInstance = CMock_Guts_MemChain(Mock.SerialIO_Print_CallInstance, cmock_guts_index);
  Mock.SerialIO_Print_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->CallOrder = ++GlobalExpectCount;
  CMockExpectParameters_SerialIO_Print(cmock_call_instance, serial, text);
}

void SerialIO_Print_AddCallback(CMOCK_SerialIO_Print_CALLBACK Callback)
{
  Mock.SerialIO_Print_IgnoreBool = (char)0;
  Mock.SerialIO_Print_CallbackBool = (char)1;
  Mock.SerialIO_Print_CallbackFunctionPointer = Callback;
}

void SerialIO_Print_Stub(CMOCK_SerialIO_Print_CALLBACK Callback)
{
  Mock.SerialIO_Print_IgnoreBool = (char)0;
  Mock.SerialIO_Print_CallbackBool = (char)0;
  Mock.SerialIO_Print_CallbackFunctionPointer = Callback;
}

void SerialIO_Print_CMockIgnoreArg_serial(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_SerialIO_Print_CALL_INSTANCE* cmock_call_instance = (CMOCK_SerialIO_Print_CALL_INSTANCE*)CMock_Guts_GetAddressFor(CMock_Guts_MemEndOfChain(Mock.SerialIO_Print_CallInstance));
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringIgnPreExp);
  cmock_call_instance->IgnoreArg_serial = 1;
}

void SerialIO_Print_CMockIgnoreArg_text(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_SerialIO_Print_CALL_INSTANCE* cmock_call_instance = (CMOCK_SerialIO_Print_CALL_INSTANCE*)CMock_Guts_GetAddressFor(CMock_Guts_MemEndOfChain(Mock.SerialIO_Print_CallInstance));
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringIgnPreExp);
  cmock_call_instance->IgnoreArg_text = 1;
}

int SerialIO_IsAvailable(SerialIO_t serial)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_SerialIO_IsAvailable_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_SerialIO_IsAvailable);
  cmock_call_instance = (CMOCK_SerialIO_IsAvailable_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.SerialIO_IsAvailable_CallInstance);
  Mock.SerialIO_IsAvailable_CallInstance = CMock_Guts_MemNext(Mock.SerialIO_IsAvailable_CallInstance);
  if (Mock.SerialIO_IsAvailable_IgnoreBool)
  {
    UNITY_CLR_DETAILS();
    if (cmock_call_instance == NULL)
      return Mock.SerialIO_IsAvailable_FinalReturn;
    Mock.SerialIO_IsAvailable_FinalReturn = cmock_call_instance->ReturnVal;
    return cmock_call_instance->ReturnVal;
  }
  if (!Mock.SerialIO_IsAvailable_CallbackBool &&
      Mock.SerialIO_IsAvailable_CallbackFunctionPointer != NULL)
  {
    int cmock_cb_ret = Mock.SerialIO_IsAvailable_CallbackFunctionPointer(serial, Mock.SerialIO_IsAvailable_CallbackCalls++);
    UNITY_CLR_DETAILS();
    return cmock_cb_ret;
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  if (cmock_call_instance->CallOrder > ++GlobalVerifyOrder)
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledEarly);
  if (cmock_call_instance->CallOrder < GlobalVerifyOrder)
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLate);
  if (!cmock_call_instance->IgnoreArg_serial)
  {
    UNITY_SET_DETAILS(CMockString_SerialIO_IsAvailable,CMockString_serial);
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(&cmock_call_instance->Expected_serial), (void*)(&serial), sizeof(SerialIO_t), cmock_line, CMockStringMismatch);
  }
  if (Mock.SerialIO_IsAvailable_CallbackFunctionPointer != NULL)
  {
    cmock_call_instance->ReturnVal = Mock.SerialIO_IsAvailable_CallbackFunctionPointer(serial, Mock.SerialIO_IsAvailable_CallbackCalls++);
  }
  UNITY_CLR_DETAILS();
  return cmock_call_instance->ReturnVal;
}

void CMockExpectParameters_SerialIO_IsAvailable(CMOCK_SerialIO_IsAvailable_CALL_INSTANCE* cmock_call_instance, SerialIO_t serial);
void CMockExpectParameters_SerialIO_IsAvailable(CMOCK_SerialIO_IsAvailable_CALL_INSTANCE* cmock_call_instance, SerialIO_t serial)
{
  memcpy((void*)(&cmock_call_instance->Expected_serial), (void*)(&serial),
         sizeof(SerialIO_t[sizeof(serial) == sizeof(SerialIO_t) ? 1 : -1])); /* add SerialIO_t to :treat_as_array if this causes an error */
  cmock_call_instance->IgnoreArg_serial = 0;
}

void SerialIO_IsAvailable_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, int cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_SerialIO_IsAvailable_CALL_INSTANCE));
  CMOCK_SerialIO_IsAvailable_CALL_INSTANCE* cmock_call_instance = (CMOCK_SerialIO_IsAvailable_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.SerialIO_IsAvailable_CallInstance = CMock_Guts_MemChain(Mock.SerialIO_IsAvailable_CallInstance, cmock_guts_index);
  Mock.SerialIO_IsAvailable_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ReturnVal = cmock_to_return;
  Mock.SerialIO_IsAvailable_IgnoreBool = (char)1;
}

void SerialIO_IsAvailable_CMockStopIgnore(void)
{
  if(Mock.SerialIO_IsAvailable_IgnoreBool)
    Mock.SerialIO_IsAvailable_CallInstance = CMock_Guts_MemNext(Mock.SerialIO_IsAvailable_CallInstance);
  Mock.SerialIO_IsAvailable_IgnoreBool = (char)0;
}

void SerialIO_IsAvailable_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, SerialIO_t serial, int cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_SerialIO_IsAvailable_CALL_INSTANCE));
  CMOCK_SerialIO_IsAvailable_CALL_INSTANCE* cmock_call_instance = (CMOCK_SerialIO_IsAvailable_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.SerialIO_IsAvailable_CallInstance = CMock_Guts_MemChain(Mock.SerialIO_IsAvailable_CallInstance, cmock_guts_index);
  Mock.SerialIO_IsAvailable_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->CallOrder = ++GlobalExpectCount;
  CMockExpectParameters_SerialIO_IsAvailable(cmock_call_instance, serial);
  cmock_call_instance->ReturnVal = cmock_to_return;
}

void SerialIO_IsAvailable_AddCallback(CMOCK_SerialIO_IsAvailable_CALLBACK Callback)
{
  Mock.SerialIO_IsAvailable_IgnoreBool = (char)0;
  Mock.SerialIO_IsAvailable_CallbackBool = (char)1;
  Mock.SerialIO_IsAvailable_CallbackFunctionPointer = Callback;
}

void SerialIO_IsAvailable_Stub(CMOCK_SerialIO_IsAvailable_CALLBACK Callback)
{
  Mock.SerialIO_IsAvailable_IgnoreBool = (char)0;
  Mock.SerialIO_IsAvailable_CallbackBool = (char)0;
  Mock.SerialIO_IsAvailable_CallbackFunctionPointer = Callback;
}

void SerialIO_IsAvailable_CMockIgnoreArg_serial(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_SerialIO_IsAvailable_CALL_INSTANCE* cmock_call_instance = (CMOCK_SerialIO_IsAvailable_CALL_INSTANCE*)CMock_Guts_GetAddressFor(CMock_Guts_MemEndOfChain(Mock.SerialIO_IsAvailable_CallInstance));
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringIgnPreExp);
  cmock_call_instance->IgnoreArg_serial = 1;
}

